export const PROJECTS = [
  {
      name: 'friendface',
     title: 'Social Media Clone',
    github: 'https://github.com/thegroosalugg/anOdeToNode/tree/main/14-RESTAPI',
      link: 'https://friendface-lyart.vercel.app/',
     stack: ['React', 'Node.js', 'Express', 'MongoDB', 'CSSModules'],
      libs: [
      'React Router',
      'Framer-Motion',
      'BCryptJS',
      'Express Validator',
      'JSONWebToken',
      'Mongoose',
      'Multer',
      'Socket.IO',
    ],
    deploy: ['Vercel', 'Render'],
  },
  {
      name: 'd-bay',
     title: 'E-Commerce Clone with STRIPE',
    github: 'https://github.com/thegroosalugg/anOdeToNode/tree/main/13-Payments',
      link: 'https://d-bay.onrender.com/',
     stack: ['EJS', 'Node.js', 'Express', 'MongoDB', 'CSS3'],
      libs: [
      'BCryptJS',
      'Express-Session',
      'Express-Validator',
      'Mongoose',
      'Multer',
      'NodeMailer',
      'Stripe',
    ],
    deploy: ['Render'],
  },
  {
      name: 'geschwindigkeitsbegrenzung',
     title: 'Timed Quiz Game',
    github: 'https://github.com/thegroosalugg/Geschwindigkeitsbegrenzung',
      link: 'https://geschwindigkeitsbegrenzu-a89a6.web.app/',
     stack: ['React', 'CSSModules'],
      libs: ['React Router', 'Framer-Motion'],
    deploy: ['Firebase'],
  },
  {
      name: 'e-harbour',
     title: 'Classified Ads Clone',
    github: 'https://github.com/thegroosalugg/eHarbour',
      link: 'https://e-harbour.vercel.app/',
     stack: ['React', 'Node.js', 'Express', 'MongoDB', 'CSSModules'],
      libs: [
      'React Router',
      'Framer-Motion',
      'BCryptJS',
      'Express Validator',
      'JSONWebToken',
      'Mongoose',
      'Multer',
    ],
    deploy: ['Vercel', 'Render'],
  },
  {
      name: 'andromeda',
     title: 'Space Themed E-Commerce Site',
    github: 'https://github.com/thegroosalugg/Andromeda',
      link: 'https://andromeda-1649b.web.app/',
     stack: ['React', 'CSSModules'],
      libs: ['React Router', 'Redux', 'Framer-Motion'],
    deploy: ['Firebase'],
  },
];
