export const USER = {
      name: 'Victor Loginov',
     title: 'FrontEnd Developer',
    github: 'https://github.com/thegroosalugg',
  linkedin: 'https://www.linkedin.com/in/vlog/',
       img: { src: '/user.png', alt: 'User Photo' },
     about: () => 'This is a paragraph. '.repeat(20),
    skills: [
    'TypeScript',
    'React',
    'Angular',
    'Node.js',
    'Express',
    'HTML5',
    'CSS3',
    'CSSModules',
    'Sass',
    'TailwindCSS',
    'Bootstrap',
    'Redux',
    'Framer',
    'Socket.io',
    'GitHub',
    'MongoDB',
    'Mongoose',
  ],
};
