export const USER = {
      name: 'Victor Loginov',
     title: 'FrontEnd Developer',
    github: 'https://github.com/thegroosalugg',
  linkedin: 'https://www.linkedin.com/in/vlog/',
    skills: [
    'typescript',
    'react',
    'angular',
    'node',
    'express',
    'html',
    'css',
    'sass',
    'tailwind',
    'bootstrap',
    'redux',
    'motion',
    'socketio',
    'github',
    'mongodb',
    'mongoose',
  ],
};
