export const USER = {
      name: 'Victor Loginov',
     title: 'FullStack Developer',
    github: 'https://github.com/thegroosalugg',
  linkedin: 'https://www.linkedin.com/in/vlog/',
     email: 'https://formspree.io/f/myzwpvlp',
       img: { src: '/user.png', alt: 'User Photo' },
    skills: [
    'TypeScript',
    'React',
    'Next.js',
    'Angular',
    'Node.js',
    'Express',
    'HTML5',
    'CSS3',
    'CSSModules',
    'Sass',
    'TailwindCSS',
    'Bootstrap',
    'Redux',
    'Framer',
    'Socket.io',
    'GitHub',
    'MongoDB',
    'Mongoose',
  ],
  about:
    "I'm a career-changer with a background in motor insurance, now focused on frontend development. I’ve trained through Le Wagon and continued with self-study, working with TypeScript, React, Node.js, and Angular 19. I enjoy building clean UIs and solving technical challenges, and I’m currently looking for junior roles in Berlin.",
};
